apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/NPCkennedy/the-monolith
    targetRevision: main
    path: apps/ntfy
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
